name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build EXE
      run: npx electron-builder --win nsis

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: GoldAI‑exe
        path: |
          dist/*.exe
